#!/bin/bash

cd Codes
./plotting_results_FCLayerwise_L2.py MNIST
./plotting_results_FCLayerwise_L2.py CIFAR10
./plotting_results_CNNLayerwise_L2.py MNIST
./plotting_results_CNNLayerwise_L2.py CIFAR10

./plotting_results_FCLayerwise_ADMM.py MNIST
./plotting_results_FCLayerwise_ADMM.py CIFAR10
./plotting_results_CNNLayerwise_ADMM.py MNIST
./plotting_results_CNNLayerwise_ADMM.py CIFAR10

