#!/bin/bash

screen -S test -d -m 
screen -S test -X exec touch HELLO
screen -S test -X exec touch WORLD
screen -S test -X chdir Codes
screen -S test -X exec /workspace/hwan/anaconda3/envs/tf_gpu/bin/python3 Training_Driver_NNLayerwise_L2.py"
