#!/bin/bash

screen -S test -d -m
screen -S test -X source /workspace/hwan/anaconda3/envs/tf_gpu/bin/activate
screen -S test -X
screen -S test -X chdir Codes
screen -S test -X exec ./Training_Driver_NNLayerwise_L2.py
