#!/bin/bash

screen -S LW_CIFAR10_NN_L2 -d -m 
screen -S LW_CIFAR10_NN_L2 -X chdir Codes
screen -S LW_CIFAR10_NN_L2 -X exec /workspace/hwan/anaconda3/envs/tf_gpu/bin/python3 Training_Driver_NNLayerwise_L2.py

screen -S LW_CIFAR10_NN_ADMM -d -m 
screen -S LW_CIFAR10_NN_ADMM -X chdir Codes
screen -S LW_CIFAR10_NN_ADMM -X exec /workspace/hwan/anaconda3/envs/tf_gpu/bin/python3 Training_Driver_NNLayerwise_ADMM.py

screen -S LW_CIFAR10_CNN_L2 -d -m 
screen -S LW_CIFAR10_CNN_L2 -X chdir Codes
screen -S LW_CIFAR10_CNN_L2 -X exec /workspace/hwan/anaconda3/envs/tf_gpu/bin/python3 Training_Driver_CNNLayerwise_L2.py

screen -S LW_CIFAR10_CNN_ADMM -d -m 
screen -S LW_CIFAR10_CNN_ADMM -X chdir Codes
screen -S LW_CIFAR10_CNN_ADMM -X exec /workspace/hwan/anaconda3/envs/tf_gpu/bin/python3 Training_Driver_CNNLayerwise_ADMM.py
