#!/bin/bash

screen -S LW_CIFAR10_NN_e15 -d -m 
screen -S LW_CIFAR10_NN_e15 -X chdir Codes
screen -S LW_CIFAR10_NN_e15 -X exec /workspace/hwan/anaconda3/envs/tf_gpu/bin/python3 Training_Driver_FCLayerwise.py

screen -S LW_CIFAR10_NN_ADMM_e15 -d -m 
screen -S LW_CIFAR10_NN_ADMM_e15 -X chdir Codes
screen -S LW_CIFAR10_NN_ADMM_e15 -X exec /workspace/hwan/anaconda3/envs/tf_gpu/bin/python3 Training_Driver_FCLayerwise_ADMM.py

screen -S LW_CIFAR10_CNN_e15 -d -m 
screen -S LW_CIFAR10_CNN_e15 -X chdir Codes
screen -S LW_CIFAR10_CNN_e15 -X exec /workspace/hwan/anaconda3/envs/tf_gpu/bin/python3 Training_Driver_CNNLayerwise.py

screen -S LW_CIFAR10_CNN_ADMM_e15 -d -m 
screen -S LW_CIFAR10_CNN_ADMM_e15 -X chdir Codes
screen -S LW_CIFAR10_CNN_ADMM_e15 -X exec /workspace/hwan/anaconda3/envs/tf_gpu/bin/python3 Training_Driver_CNNLayerwise_ADMM.py
